" .vimrc

" load up pathogen
call pathogen#infect()
call pathogen#helptags()

" don't need to be compatible with old vim
set nocompatible

" set leader key to comma
let mapleader = ","

" map command-t
map <D-N> :CommandTFlush<cr>\|:CommandT<cr>

" map Ack
map <D-F> :Ack<space>

" map NERDTree
map \ :NERDTreeToggle<CR>

" autocomplete (insert mode)
set complete=.,w,b
set pumheight=10
set completeopt=menu

" autocomplete (command line mode)
set wildmode=list:longest

" clear the command line and search highlighting
noremap <C-l> :nohlsearch<CR><C-l>

" regenerate tags, with or without gemhome included
map <leader>rt :!ctags -R --exclude=.git --exclude=log *<CR>
map <leader>rT :!ctags -R --exclude=.git --exclude=log * `rvm gemhome`/*<CR>

" map autocomplete
inoremap <C-Space> <C-n>
inoremap <M-Space> <C-p>

" map %% to current directory
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" move between splits more easily
map <C-J> <C-W>w
map <C-K> <C-W>W

" show line numbers
set nu

" show row and column in footer
set ruler

" minimum lines above/below cursor
set scrolloff=2

" disable code folding
set nofoldenable

" put useful info in status bar
set statusline=%F%m%r%h%w\ [%l,%c]\ [%L,%p%%]

" always show status bar
set laststatus=2

" show extra space characters
set list listchars=tab:»·,trail:·

" toggle spellcheck with <F5>
:map <F5> :setlocal spell! spelllang=en_au<cr>
:imap <F5> <ESC>:setlocal spell! spelllang=en_au<cr>

" show syntax highlighting
syntax on

" we have a dark background
set background=dark
colorscheme solarized

" set auto indent
set autoindent
filetype plugin indent on

" set indent to 2 spaces and expand
set ts=2
set shiftwidth=2
set expandtab

" show bracket matches
set showmatch

" ignore case in search
set ignorecase

" highlight all search matches
set hlsearch

" pay attention to case when caps are used
set smartcase

" show search results as I type
set incsearch

" enable mouse support
set mouse=a

" enable visual bell (disable audio bell)
set vb

" enable bash style tab completion
set wildmenu
set wildmode=list:longest,full

" highlight long lines
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.*/
