" .vimrc

" load up pathogen
call pathogen#infect()
call pathogen#helptags()

syntax on " show syntax highlighting
filetype plugin indent on
set autoindent " set auto indent
set ts=2 " set indent to 2 spaces
set shiftwidth=2
set expandtab
set nocompatible " don't need to be compatible with old vim
set showtabline=2 " always show tab bar
set nu " show line numbers
set showmatch " show bracket matches
set ignorecase " ignore case in search
set hlsearch " highlight all search matches
set cursorline " higlight current line
set smartcase " pay attention to case when caps are used
set incsearch " show search results as I type
set mouse=a " enable mouse support
set vb " enable visual bell (disable audio bell)
set ruler " show row and column in footer
set scrolloff=2 " minimum lines above/below cursor
set laststatus=2 " always show status bar
set list listchars=tab:»·,trail:· " show extra space characters
set wildmenu " enable bash style tab completion
set wildmode=list:longest,full

" put useful info in status bar
set statusline=%F%m%r%h%w\ %{fugitive#statusline()}\ [%l,%c]\ [%L,%p%%]

" set dark background and colorscheme
set background=dark
colorscheme solarized
" let g:solarized_termcolors=256

" highlight currently searched word
hi! IncSearch cterm=inverse

" clojure: turn on rainbow parens
let g:vimclojure#ParenRainbow=1

" set leader key to comma
let mapleader = ","

" unmap F1 help
nmap <F1> :echo<CR>
imap <F1> <C-o>:echo<CR>

" map command-t
map <leader>f :CommandT<cr>

" close command-t with C-x
let g:CommandTCancelMap='<C-x>'

" map fugitive git commands
map <leader>gs :Gstatus<cr>
map <leader>gb :Gblam<cr>

" map Ack
map <leader>a :Ack!<space>

" clear the command line and search highlighting
noremap <C-l> :nohlsearch<CR>

" regenerate ctags
" map <leader>rt :!ctags -R --exclude=.git --exclude=log *<CR>

" map %% to current directory
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" toggle spellcheck with <F5>
map <F5> :setlocal spell! spelllang=en_us<cr>
imap <F5> <ESC>:setlocal spell! spelllang=en_us<cr>

" hint to keep lines short
if exists('+colorcolumn')
  set colorcolumn=80
endif
