#!/bin/sh

set -e

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

echo "==> Here we go..."
cd ~

echo "  > Pulling latest dot-files..."
git pull &> /dev/null

echo "  > Installing Neovim, ripgrep, NPM, GitHub..."
brew install neovim rg npm zsh-syntax-highlighting gh rbenv tmux

echo "  > Installing Pure prompt..."
git clone git@github.com:sindresorhus/pure.git .zsh/pure

echo "  > Installing vim plugins..."
vim +PlugInstall +qall

echo "==> Done with setup."
