#!/bin/sh

set -e
cd ~

./script/setup

echo "==> Updating all the things..."

echo "  > Pulling master for all vim submodules..."
cd ~
git submodule foreach git pull origin master &> /dev/null

echo "==> Updating oh-my-zsh..."
echo "  > Rebasing against upstream..."
cd ~/.oh-my-zsh
git fetch upstream && git rebase upstream/master &> /dev/null

echo "  > Pulling master for all submodules..."
cd ~/.oh-my-zsh
git submodule foreach git pull origin master &> /dev/null

echo "==> Done updating."
cd ~
git status -s -b
